services:
  - type: web
    name: malut-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
